kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 namespace: argocd
 name: argo-repo-server-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
