apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample2-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shailsirohi/argocd-sample-repo
    targetRevision: HEAD
    path: sample2
    plugin:
      name: argocd-vault-plugin
      env:
        - name: AVP_SECRET
          value: secretsmanager-creds
  destination:
    server: https://kubernetes.default.svc
    namespace: sample
